name: Pipeline
on:
  push:
    branches:
      - master
      - feature/ci
      - release/*

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Prepare
        run: |
          git config --global user.email "danielrichter@posteo.de"
          git config --global user.name "Github Actions"
          npm ci
      - name: Install
        env:
          # Need to set a valid env, otherwise npm complains with "Failed to replace env in config: ${NPM_TOKEN}"
          NPM_TOKEN: DUMMY
        run: |
          npx gulp ci
      - name: Build
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp build
      - name: Checksum
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp checksum
          git add .
          git commit -asm "chore: checksum"
      - name: Test
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp test
      - name: Version
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp version
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/danielr1996/bumpup.git"
          git push "${remote_repo}" ${GITHUB_REF#"refs/heads/"} --follow-tags
      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npx gulp publish
